---
title: "pcda final project scraping"
author: "sipos"
date: "2024-12-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

reading the manifestos

```{r}
library(tidyverse)
library(stringr)
d_pis <- read_csv("https://i.amcat.nl/pis.csv")
```

```{r}
library(tidyverse)
library(stringr)
d_ko <- read_csv("https://i.amcat.nl/ko.csv")
```

looking for the pages that have words related to immigration in PiS's manifesto

```{r}
library(tidyverse)
library(stringr)
pis_immigration <- select(d_pis,text) |>
  filter(str_detect(text, regex("imigracj\\w+|migracj\\w+|polityka migracyjn\\w+|imigran\\w+|uchodź\\w+", ignore_case = TRUE)))
```

```{r}
library(tidytext)
library(tidyverse)
library(ggwordcloud)
library(stopwords)

polish_stopwords <- stopwords("pl", source = "stopwords-iso")

pis_immigration2 <- pis_immigration |>
  unnest_tokens(word, text) |>
  group_by(word) |> 
  summarize(n = n()) 
pis_immigration_cleaned <- pis_immigration2 |>
  filter(n >= 2, 
         !word %in% polish_stopwords, 
         str_length(word) >= 2) |>
  arrange(-n) |>
  slice_head(n=100) 
ggplot(pis_immigration_cleaned) + 
  geom_text_wordcloud(aes(label=word, size=n, color=n)) +
   theme_void()
```

looking for the pages that have words related to immigration in KO's manifesto

```{r}
library(tidyverse)
library(stringr)
ko_immigration <- select(d_ko,text) |>
  filter(str_detect(text, regex("imigracj\\w+|migracj\\w+|polityka migracyjn\\w+|imigran\\w+|uchodź\\w+", ignore_case = TRUE)))
```

```{r}
library(tidytext)
library(tidyverse)
library(ggwordcloud)
library(stopwords)

polish_stopwords <- stopwords("pl", source = "stopwords-iso")

ko_immigration2 <- ko_immigration |>
  unnest_tokens(word, text) |>
  group_by(word) |> 
  summarize(n = n()) 
ko_immigration_cleaned <- ko_immigration2 |>
  filter(n >= 2, 
         !word %in% polish_stopwords, 
         str_length(word) >= 2) |>
  arrange(-n) |>
  slice_head(n=100) 
ggplot(ko_immigration_cleaned) + 
  geom_text_wordcloud(aes(label=word, size=n, color=n)) +
   theme_void()
```